### ISSUE TITLE
deadlocked indexer threads

### ISSUE THREAD

**Issue by TTimo** [CoatiSoftware/SourcetrailBugTracker#616]
The indexers are deadlocking in 2018_3_54 - this is new and 100% reproductible for me on this new release (Linux x86_64)

```
(gdb) bt
#0  0x00007fe9a70296d6 in futex_abstimed_wait_cancelable (private=128, abstime=0x0, expected=0, futex_word=0x7fe9a7cd1000) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x7fe9a7cd1000, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007fe9a70297c8 in __new_sem_wait_slow (sem=0x7fe9a7cd1000, abstime=0x0) at sem_waitcommon.c:181
#3  0x000000000093cc2c in SharedMemory::ScopedAccess::ScopedAccess(SharedMemory*) ()
#4  0x00000000008ce935 in InterprocessIndexingStatusManager::startIndexingSourceFile(FilePath const&) ()
#5  0x00000000008addec in InterprocessIndexer::work() ()
#6  0x0000000000813055 in main ()
```

**Comment by TTimo** [comment]
This happens if I reduce the number of indexers to 1 as well .. same backtrace. This suggests it's between the indexer and the main GUI process then?

**Comment by egraether** [comment]
There haven't been any changes related to shared memory since 2018.3.13. The issue was not present in the last release?

Did you try rebooting your machine? We had issues with shared memory where that helped.

**Comment by TTimo** [comment]
I moved back to previous release and reindexed with 8 threads (no reboot in between), and encountered no lockups.

**Comment by egraether** [comment]
Is this happening in every project?

**Comment by TTimo** [comment]
The first 1900 or so files out of ~ 2000 fly by really quickly in the new version, but the progress dialog doesn't change. It almost looked like a "prepass" considering the previous indexing speeds. Then it usually locks up somewhere between 1940 and 1970.

https://gyazo.com/f800d3dd756dc8a1480286d51e14ccb1

I don't have any other projects ready to go, but I'll check when I get a chance.

**Comment by egraether** [comment]
I see, then the real problem is most likely #617, which causes every indexer process to crash on every source file, which if happening a lot can somehow cause shared memory mutexes to not properly unlock, causing deadlocks.

**Comment by egraether** [comment]
#617 is closed now, but we will keep this open, because this is a separate issue that can occur when an indexer process crashes.
